### ISSUE TITLE
Consider adding DeviceSQL

### ISSUE THREAD

**Issue by deliciouslytyped** [cmu-db/dbdb.io#109]
I stumbled some information:

- https://www.quora.com/What-is-the-worlds-smallest-SQL-capable-database/answer/Greg-Kemnitz
- https://www.ubiquitous-ai.com/en/products/storage/devicesql/

- https://www.st.com/en/partner-products-and-services/ubiquitous-devicesql.html#overview (and various other embedded manufacturer pages)

- https://sqlite-users.sqlite.narkive.com/nDXkscBX/devicesql#post2

It seems like it may be an interesting system to include on dbdb.io, though I'm not entirely sure given the narkive mailing list thread.
Searching Google for "DeviceSQL" seems to yield generally relevant, and not that many, results.

**Comment by apavlo** [comment]
Thank you @deliciouslytyped: https://dbdb.io/db/devicesql
