### ISSUE TITLE
Adding Copernic

### ISSUE THREAD

**Issue by amirouche** [cmu-db/dbdb.io#118]
Hi dbdb team,

Could you please help to add the [copernic](https://git.sr.ht/~amirouche/copernic) to the database?

Copernic is web application that is (mostly) implemented with Python programming language. It is supported by a database that is a versioned triple store. It is possible to do time traveling queries at any point in history while still being efficient to query and modify the latest version. The versioned triple store is implemented using a novel approach dubbed generic tuple store. copernic goal is to demonstrate that versioned databases allow to implement workflows that ease cooperation such as pull requests.

Thanks for your consideration

**Comment by apavlo** [comment]
@amirouche Email me and we can discuss this.
