### ISSUE TITLE
Shows multiple instances of the same DBMS by commit

### ISSUE THREAD

**Issue by abigalekim** [cmu-db/dbdb.io#119]
I understand the importance of showing difference instances of the same DBMS by commit (for instance, a DBMS could've lost compatibility with another at some point and then regained it?). But I think this is kind of annoying to look at. Maybe keep track of the commits that actually modify the particular field?

(this should say 1 and only include the last revised version, I think)
https://dbdb.io/browse?inspired=scidb

**Comment by apavlo** [comment]
This is a limitation of Xapian. We need to switch to Postgres: https://github.com/cmu-db/dbdb.io/pull/117
