### ISSUE TITLE
Using the search box on a individual db's page, results in the browser being redirected to 127.0.01

### ISSUE THREAD

**Issue by bgianfo** [cmu-db/dbdb.io#12]
__Repro:__
 1. Navigate to some awesome DB on the site, like http://dbdb.io/db/Microsoft-SQL-Server 
 2. Search for something in the search box in the top right corner.
 3. Browser will be redirected to: http://127.0.0.1:8000/db/<search-term>

**Comment by apavlo** [comment]
Thanks, but the site is not public yet. We're still working on it.
