### ISSUE TITLE
Datomic is now free

### ISSUE THREAD

**Issue by eggsyntax** [cmu-db/dbdb.io#120]
Datomic remains commercial but is now free (though not open source) under an Apache license. Thought y'all might want to make mention of that. Details at this blog post: https://blog.datomic.com/2023/04/datomic-is-free.html

**Comment by apavlo** [comment]
@eggsyntax Updated! Thanks! https://dbdb.io/db/datomic/revisions/16

**Comment by eggsyntax** [comment]
Thank YOU for such an awesomely useful project!
