### ISSUE TITLE
how to DB info update and add new DB

### ISSUE THREAD

**Issue by Lena-Ev** [cmu-db/dbdb.io#121]
Is there a way to update outdated information about InterSystems DBMS, remove and add new ones?
new one:
https://www.intersystems.com/data-platform/
Those are outdated (used by some old users, but are not developing)
<img width="998" alt="image" src="https://user-images.githubusercontent.com/77621970/236761109-d7907a86-2eb5-433e-b49e-7c090fa7182e.png">
https://dbdb.io/browse?q=intersystems

**Comment by apavlo** [comment]
@Lena-Ev Can you email me and we can work out logistics on how to update these?
