### ISSUE TITLE
Unable to filter results - 404 for browse.js

### ISSUE THREAD

**Issue by tangledbytes** [cmu-db/dbdb.io#136]
Hi, thank you for maintaining this site.

Lately I cannot filter the results because the "show all" won't work or the date slider won't show up. I have noticed that for some reason I am getting 404 for `/static/core/js/browse.js` which I suspect is the RC.

I went to wayback machine and I think it was working fine till 27th June 2023.

I am willing to push a fix (if needed).

**Comment by apavlo** [comment]
@tangledbytes Thanks for heads up! It turns out I forgot to use Django's static file installation command on the web server. It should be working now:

view-source:https://dbdb.io/static/core/js/browse.js
