### ISSUE TITLE
Create options for unused fields

### ISSUE THREAD

**Issue by aquafemi** [cmu-db/dbdb.io#17]
Fields like Derived From and Project Type don't have any way of actually being edited. They should be treated similar to other metadata such as OSes or description so you can select options for them.

Also need to decide what to do with some unused fields such as tech_docs, logo_img, logo, dbmodels,  licenses, access_methods, default_isolation, and max_isolation.

Also many tables have a "website" column that isn't set. Maybe website should be removed or have some way of being set. Should the website be changed to a slug? If so does there need to be some sort of view for every thing with a slug?

**Comment by aquafemi** [comment]
**Metadata**
tech_docs - url to documentation
developer - developer
logo - original image (preferable svg)
logo_img - thumbnail (png, we automatically generate this using python PIL)

**Options**
default_isolation, max_isolation - two new feature option, choices come from ISOLATION_LEVELS

**Comment by dvanaken** [comment]
@aquafemi I'm not able to edit the metadata fields (e.g., developer, start date, etc.). Do we support editing for these fields?

**Comment by aquafemi** [comment]
Related to issue #18
