### ISSUE TITLE
Cannot upload database logo

### ISSUE THREAD

**Issue by dvanaken** [cmu-db/dbdb.io#18]
In edit mode, I upload a new database logo but it does not persist after I press the save button.

**Comment by ShuxinLin** [comment]
I added something in `Developers`, `start date`, `logo`. After I saved, those fields are still blank.

<img width="999" alt="screen shot 2017-04-28 at 4 21 07 pm" src="https://cloud.githubusercontent.com/assets/8956612/25545953/dcb38c68-2c2e-11e7-9417-905d33b1f208.png">


After I saved,


<img width="1051" alt="screen shot 2017-04-28 at 4 21 24 pm" src="https://cloud.githubusercontent.com/assets/8956612/25546001/106beb18-2c2f-11e7-9b89-345f9dc6dbea.png">

**Comment by aquafemi** [comment]
Hi there, thanks for reporting. I just pushed a hotfix for this to the repository. The actual change will be applied to the live website in a few days. The update logo feature is not ready yet so that will be removed for the time being.

**Comment by apavlo** [comment]
I updated the website.

@ShuxinLin Can you try it again?

**Comment by ShuxinLin** [comment]
The website seems down now...

![screen shot 2017-04-29 at 11 46 18 am](https://cloud.githubusercontent.com/assets/8956612/25556799/8db744b2-2cd1-11e7-9546-bf16746462c4.png)

**Comment by apavlo** [comment]
Ugh, that is my fault. I will fix when I get back to my desk

**Comment by apavlo** [comment]
@aquafemi What do you want me to do here:

```
warsteiner:/usr0/www/dbdb.io# python manage.py migrate
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Operations to perform:
  Apply all migrations: admin, contenttypes, auth, sessions
Running migrations:
  No migrations to apply.
The following content types are stale and need to be deleted:

    systems | apiaccessmethod

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: no
```

**Comment by aquafemi** [comment]
Yes it can be deleted.

**Comment by apavlo** [comment]
@aquafemi I deleted it but I still get an error:

http://dbdb.io/

**Comment by aquafemi** [comment]
@apavlo Are you sure the website has been updated from master? The line that the error occurs on doesn't correspond with the line of the file on master.

**Comment by aquafemi** [comment]
Ok, it looks like it is current. The problem is probably that the database has unapplied migrations.

**Comment by aquafemi** [comment]
This should now be fixed, as well as saving in general.
