### ISSUE TITLE
Task List (April 1st)

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#3]
1. Make the system website a clickable URL (href)
2. Add "System Manager" to admin list
3. Change "System" to "Revision". Change "System Manager" to "System"
4. Add the ability to toggle a red "X" if a system doesn't have a feature.
5. Markdown rendering doesn't work.
6. Move the righthand info panel to be aligned to the top.
7. Add version info + date to the top right corner of page.
8. When importing system information, make the start/end date be null if it is zero.
9. Hide the feature categories if it is not known whether it has it. The editing page should still show everything.

**Comment by rnvarma** [comment]
- 1 Make the system website a clickable URL (href)

- 2 Add "System Manager" to admin list

- 6 Move the righthand info panel to be aligned to the top.

Completed

**Comment by aquafemi** [comment]
3. Done but System is now SystemVersion
4. Done
5. Done
8. Done

Pending:
7. Still desired?
9. I think this is done but support toggles between supported and unsupported and can't be unknown.
