### ISSUE TITLE
Add Support For Additional Search Filters

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#44]
There are the additional meta-data fields for systems that we are not able to search on right now. The only meta-fields that we currently support are the following:

1. Compatible With: https://dbdb.io/browse?compatible=mysql
2. Derived From: https://dbdb.io/browse?derived=tikv
3. Inspired By: https://dbdb.io/browse?inspired=spanner
4. Country: https://dbdb.io/browse?country=US

-----------------

We need to add filtering for these additional fields:

1. Operating System
2. Programming Languages
3. Project Type
4. Licenses

We also need to support mixing the filters. It looks like we support that now but the search result label only includes the one of the filters:

https://dbdb.io/browse?derived=postgresql&country=US

This because the template code is just a bunch of if-else statements:

https://github.com/cmu-db/dbdb.io/blob/master/templates/core/database-browse.html#L113-L149

-----------------

I don't know if there is a more generic way we should be performing these searches or whether it should be ad-hoc like we are doing now:

https://github.com/cmu-db/dbdb.io/blob/master/dbdb/core/views.py#L307-L346

**Comment by pembo13** [comment]
The index will need to be rebuilt: `python manage.py rebuild_index --noinput`
