### ISSUE TITLE
First submission always fails

### ISSUE THREAD

**Issue by DarkForte** [cmu-db/dbdb.io#47]
The first time I submit a revision, it will always fail and prompt me to enter the "database name", which mysteriously disappears from the title. And my revision comment is gone. I have to manually fill in the title and re-enter my revision comment to submit a revision.

![image](https://user-images.githubusercontent.com/8542129/48961248-07593680-ef41-11e8-9ef8-00ea0715ac16.png)

The screenshot is what I see after I submit the first time. The name and comments are gone. If I submit again from this page it will be okay.

Thanks!

**Comment by apavlo** [comment]
What system are you editing?

**Comment by manifoldQAQ** [comment]
Same here. Also, urls seem to mess up on the second submission.

**Comment by cczhong11** [comment]
Same here.

**Comment by ethanywang** [comment]
Same here. And In the second time, we need to input the database name field.

**Comment by apavlo** [comment]
Oh I think I know what this is. Let me see if I can fix.

**Comment by apavlo** [comment]
Fixed in 41a0a14daa3ae160ff1428da5d28533f24bbcc8a
