### ISSUE TITLE
Browse page is super slow

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#49]
I finally deployed the latest version of the website. Unfortunately the 'browse' page is slow:

https://dbdb.io/browse

Each refresh takes over 10 seconds to load. I disabled loading the `other_filtersgroups` in `DatabaseBrowseView`, but it didn't make a difference.

Is there something obvious that we are doing wrong?

**Comment by apavlo** [comment]
I rolled back to 8fb8c49fded63802cc4758613eec89a99e93b1e2.

I've attached a profile generated locally:
[silk.pdf](https://github.com/cmu-db/dbdb.io/files/2715977/silk.pdf)

**Comment by pembo13** [comment]
@apavlo I'm looking at this right now. It would be great if I could get a copy of the live database please.

**Comment by pembo13** [comment]
actually a copy of the images would be good as well... I should probably implement lazy-loading on the images.

**Comment by apavlo** [comment]
I will email you everything.

**Comment by pembo13** [comment]
@apavlo let me know if you're okay for me to proceed with with the Xapian backend, per my email.

**Comment by apavlo** [comment]
@pembo13 Just responded. Go ahead! Thanks

**Comment by pembo13** [comment]
@apavlo changes have been committed as described.

Please remember to complete install of Xapain, included the build script in git:

    $ wget https://raw.githubusercontent.com/notanumber/xapian-haystack/master/install_xapian.sh
    $ chmod +x install_xapian.sh
    $ ./install_xapian.sh 1.4.9
    $ pip install git+https://github.com/notanumber/xapian-haystack.git
    $ mkdir data/xapian
    $ python manage.py rebuild_index --noinput # after changing the settings.py appropriately

**Comment by apavlo** [comment]
@pembo13 New search index is fast! Running live now! Thanks!
