### ISSUE TITLE
Task List (April 22nd)

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#5]
1. Advanced search shouldn't preload the entire data set. Show an alphabetical list of the DBMSs (without an occlusion). Search panel at the top should have a _Refresh_ button. 
2. On the system page, make the last version date smaller. Move to the right-hand side. Say something "Last updated XYZ". Remove version # and comment.
3. Add keyword search to the advanced search page. We will need to upgrade to MySQL 5.6 to get full text indexes: https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html

**Comment by aquafemi** [comment]
2. Done

Pending:
1. Still desired? What should the refresh do?
3.
