### ISSUE TITLE
[question] how to add other dbs?

### ISSUE THREAD

**Issue by seralf** [cmu-db/dbdb.io#51]
Hi thanks for the really nice project, it's awesome! :-)

I wonder is there is a way to suggest the addition of other databases, in case they are not present in the index?

PS: I would also suggest to create a page listing the technologies used, it could be useful for others

**Comment by apavlo** [comment]
What DBMSs do you think are missing?

What do you mean by "technologies"?

**Comment by seralf** [comment]
I didn't find references to RDF4J (the "new" sesame stack, that it's better
to maintain distinct, since this "new" package is maintained by the eclipse
foundation).
I wonder if virtualization technoogies should be cited or not? such as
Drill, Dremio, calcite. Even if they are not truly databases, they play
that roles in the context of hadoop ecosystem, for example, in a similar
way as sparkSQL does.
Generally speaking it would be great if other people could add new db by
editing a file on their fork, and send a PR: this approach is used in
wappalyzer project, for example, and it seems to work well :-)
With "technologies" I suggested that you could add an explanation on the
stack you are currently using, since it could be useful to other.

my 2 cents

thanks for the good work




Il giorno mer 27 feb 2019 alle ore 00:44 Andy Pavlo <
notifications@github.com> ha scritto:

**Comment by vertexclique** [comment]
@apavlo I would like to add our recent DB system. How can I add it to the index or is it possible to add it?

**Comment by apavlo** [comment]
@vertexclique Email me.
