### ISSUE TITLE
De-select in Compatible With

### ISSUE THREAD

**Issue by JiaqiLiu** [cmu-db/dbdb.io#63]
Hi, maybe a de-selection is needed in "Compatible With" and other similar checkboxes.

**Comment by pembo13** [comment]
@apavlo I wasn't really able to understand this request. On the browse page, there's already a hover-over action to "Clear All".

**Comment by apavlo** [comment]
I don't remember what this was. The new search "tags" is probably what I meant. They are working great!

https://dbdb.io/browse?country=CN
