### ISSUE TITLE
Monthly Homepage Snapshots

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#66]
The homepage has three "top 5" lists:  (1) most recently updated, (2) most visits, and (3) most edits. The problem is that the most visits and most edits are from all time, so they almost never change. The only thing that changes is the most recently updated.

I instead would like to have the ability to compute a snapshot of the most visits and edits from previous month. It would run as a management command (thank you for teaching me about them!) in a cronjob once a month. Then the homepage would just retrieve the latest snapshot and show that.

**Comment by pembo13** [comment]
@apavlo what do you think of doing a rolling 30-day window instead? That could be done with some model tweaks and SQL, instead of needing to do snapshots.

For example, to get the most edited:

    start_date = timezone.now().astimezone(pytz.utc) - datetime.timedelta(days=30)
    start_date = datetime.datetime.combine(start_date.date(), datetime.time(0, 0, 0))
    start_date = pytz.utc.localize(start_date)

    most_versions = System.objects \
        .annotate(num_versions=Count('versions__id', filter=Q(versions__created__gte=start_date))) \
        .order_by('-num_versions', '-name') \
        .filter(num_versions__gt=0)
    for s in most_versions[:items_to_show]:
        print(s, s.num_versions)

**Comment by apavlo** [comment]
@pembo13 I am okay with 30-day windows. This would be a reasonable compromise. Let's go with this idea.

**Comment by pembo13** [comment]
@apavlo I was actually able to do this in the end with no model changes, and actually removed (commented out) two DB queries in the counter code.
