### ISSUE TITLE
Registration Referral Code

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#67]
I added the ability to set permissions on what account is allowed to edit what system:

https://github.com/cmu-db/dbdb.io/blob/master/dbdb/core/models.py#L213-L229

But right now I have to manually set it in the admin panel. What I want to be able to do is give somebody a "referral code" that is a encrypted list of system ids and then they would enter that in on the registration page. This would then automatically create the ACLs for them to edit those systems. I want to be able to make it easier for students in my class to register and get permission for their system.

I started working on this over the summer but I couldn't figure out how to modify the registration form:

https://github.com/cmu-db/dbdb.io/commit/b147132679c2ec1bfd525b1b3a97e8a778a3529c

You will see in the above commit that I have already created the 'create_acl_key.py' management command for you.

**Comment by pembo13** [comment]
Setup page at /user/setup, for example: http://dbdb.devpreviews.com/user/setup

**Comment by apavlo** [comment]
@pembo13 The demo page doesn't work. Do you want the latest snapshot of the production database?

**Comment by pembo13** [comment]
Sorry, I didn't have my dev server up.

Sure, that might be useful to have.
