### ISSUE TITLE
How to contribute (to the content)?

### ISSUE THREAD

**Issue by nblintao** [cmu-db/dbdb.io#72]
I'd like to help contribute to some of the contents in DBDB. Am I able to do it on the website? Or shall I send the changes to someone?

I already have an account (I took 15721 a few years ago) and I'm able to login. But it seems not help.

BTW The listed email is not reachable, as https://github.com/cmu-db/dbdb.io/issues/71 pointed out.

**Comment by apavlo** [comment]
Tao - Just email me directly.

**Comment by nblintao** [comment]
Cool!

**Comment by carehart** [comment]
Thanks for your efforts here. If we may just want to propose a correction to content about a db, would you have us email you (via the address offered in your cmu site profile)? Or could/should we offer it as an issue here?

**Comment by apavlo** [comment]
Email my @cs.cmu.edu account
