### ISSUE TITLE
De-prioritize country of origin

### ISSUE THREAD

**Issue by mcint** [cmu-db/dbdb.io#74]
Hello! I'm confused and distracted by the "country of origin" statistics, and their high prioritization within the site. For me, it doesn't address concerns I would have about prioritizing a database to use, extend, study, or recommend. (Though I suppose it's a fun-to-note differentiator, I see from the #10 issue that its desired, but not why.)

Might you welcome a PR to move the category to the bottom of the ~"Refine by" filter and~ /stats page?

I'm so excited about using dbdb.io as a succinct reference, I bookmarked it as I first loaded a link.

**Comment by apavlo** [comment]
It shows up at the top of the browse search options because the label "Country" appears first alphabetically for those options.

Send a PR if you have a better solution.
