### ISSUE TITLE
Add "compatibility" multi-field

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#8]
We want to include a multi-selection list that specifies a DBMS's compatibility with other DBMSs. For example, there are some systems that tout their ability to be MySQL compatible even though the architecture is completely new.

I think that this field should have the same setup as the "derived from" field where its a foreign key in the system table that points back to the system table. But it needs to support multiple selections.

**Comment by rnvarma** [comment]
side panel thing

**Comment by aquafemi** [comment]
Still desired?
