### ISSUE TITLE
Is the actual data available?

### ISSUE THREAD

**Issue by davikor** [cmu-db/dbdb.io#82]
I am currently working on a database survey article and therefore need to systematically review databases for a certain feature. To achieve this efficiently, I would love to have a list containing the name of each database along with the url of its homepage (and potentially an identificator if you are interested in updating your data with the result of our review in the end), because this seems faster than clicking on each database on dbdb.io, waiting for the site to load and then continue to the databases homepage. However, it seems the actual data of dbdb.io can not be downloaded from github or dbdb.io. Therefore my question: is it possible to get a snapshot of dbdb.ios underlying data or are you keeping these as your asset (I would be totally fine with that, of course)?

**Comment by apavlo** [comment]
Email me and I can try to get you what you need. There is a PR for a REST API (#70) but I haven't had time to test it.
