### ISSUE TITLE
The information of Apache ShardingSphere needs to be updated

### ISSUE THREAD

**Issue by YuChen-C4** [cmu-db/dbdb.io#96]
hello! I'm the Operator of SphereEx, I see ShardingSphere is included in the dbdb.io, but the content is incomplete. And the developer of ShardingSphere is not Dangdang, but Apache.

Do we have any methods to modify and supplement the content?

https://dbdb.io/db/shardingsphere

**Comment by apavlo** [comment]
Email me.
